### PR TITLE
Eobs 298 review frequency fix

### PR DESCRIPTION
**Pull request by technotariat**
- Adding is_valid() method to notification model as will use this in client config to conditionally stop notifications from being completed if no longer valid
- Broke out the mobile controller functions so less repetitive

### CODE REVIEW

**Review by homostellaris — APPROVED** [review]
LGTM :shipit:

**Comment by moderatemisbehaviour** [comment]
Looks lovely :shipit:

**Comment by moderatemisbehaviour** [comment]
Latest changes are fine :shipit:

**Comment by moderatemisbehaviour** [comment]
phwoar :shipit

**Comment by moderatemisbehaviour** [comment]
:shipit: says yes.

**Comment by Nayira** [comment]
Tests for EOBS-298, EOBS-504, EOBS-512, EOBS-513 and EOBS-529 have Passed :shipit:

**Pull request merged**
